# check tmux version
# tmux -V
# tmux 1.6


# 修改前导键
# unbind C-b
# set -g prefix C-w


# 载入配置 reload config
# prefix, r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

set -g mode-mouse on
set -g mouse-select-pane on
set -g mouse-resize-pane on
set -g mouse-select-window on



# 选中窗口
bind-key k select-pane -U
bind-key j select-pane -D
bind-key h select-pane -L
bind-key l select-pane -R

# 分割窗口使用更加直观的快捷键
unbind '"'
bind - splitw -v
unbind %
bind | splitw -h
