
USERNAMEBASE=temp
USERINDEX=10
USERCOUNT=20
while [ $USERINDEX -le $USERCOUNT ]
do
	useradd $USERNAMEBASE$USERINDEX -m
	echo "$USERNAMEBASE$USERINDEX:$USERNAMEBASE$USERINDEX""123" |chpasswd
	USERINDEX=`expr $USERINDEX + 1` 
done

